In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df2 = pd.read_csv("/mntSDB/carlos.simoes/GithubProjects/MHCXGraph/chunkTests/ca_only/mel5_10_2/MULTIPLE/nodes_per_protein.csv")
df5 = pd.read_csv("/mntSDB/carlos.simoes/GithubProjects/MHCXGraph/chunkTests/ca_only/mel5_10_5/MULTIPLE/nodes_per_protein.csv")
df6 = pd.read_csv("/mntSDB/carlos.simoes/GithubProjects/MHCXGraph/chunkTests/ca_only/mel5_10_6/MULTIPLE/nodes_per_protein.csv")
df9 = pd.read_csv("/mntSDB/carlos.simoes/GithubProjects/MHCXGraph/chunkTests/ca_only/mel5_10_9/MULTIPLE/nodes_per_protein.csv")

In [21]:
(df2 == df5)

,component_id,frame_id,protein_index,protein_key,protein_name,total_nodes_associated,total_nodes_original,pep_orig_nodes,mhc_orig_nodes,frame_nodes_instances,frame_nodes_unique,node_coverage,duplication_ratio,duplication_rate,avg_multiplicity,unique_nodes_per_chain
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
950,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
951,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
952,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
953,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [20]:
(df2 == df9).all()

component_id               True
frame_id                   True
protein_index              True
protein_key                True
protein_name               True
total_nodes_associated    False
total_nodes_original       True
pep_orig_nodes             True
mhc_orig_nodes             True
frame_nodes_instances     False
frame_nodes_unique        False
node_coverage             False
duplication_ratio         False
duplication_rate          False
avg_multiplicity          False
unique_nodes_per_chain    False
dtype: bool

In [18]:
df2[(df2 != df9).any(axis=1)]

,component_id,frame_id,protein_index,protein_key,protein_name,total_nodes_associated,total_nodes_original,pep_orig_nodes,mhc_orig_nodes,frame_nodes_instances,frame_nodes_unique,node_coverage,duplication_ratio,duplication_rate,avg_multiplicity,unique_nodes_per_chain
0,0,0,0,0,bst2_renamed,1076,49,7,42,1076,41,0.836735,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
1,0,0,1,1,dse_renamed,1076,48,6,42,1076,41,0.854167,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
2,0,0,2,2,erbb2_renamed,1076,49,6,43,1076,41,0.836735,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
3,0,0,3,3,imp1_renamed,1076,48,5,43,1076,41,0.854167,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
4,0,0,4,4,imp2_renamed,1076,48,5,43,1076,41,0.854167,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
5,0,0,5,5,melana_renamed,1076,49,6,43,1076,42,0.857143,0.039033,0.960967,25.619048,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
6,0,0,6,6,mrp3_renamed,1076,47,4,43,1076,41,0.872340,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
7,0,0,7,7,muc16ats_renamed,1076,48,5,43,1076,41,0.854167,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
8,0,0,8,8,muc16tss_renamed,1076,50,6,44,1076,41,0.820000,0.038104,0.961896,26.243902,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
9,1,0,0,0,bst2_renamed,1064,49,7,42,1064,41,0.836735,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
10,1,0,1,1,dse_renamed,1064,48,6,42,1064,41,0.854167,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
11,1,0,2,2,erbb2_renamed,1064,49,6,43,1064,41,0.836735,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
12,1,0,3,3,imp1_renamed,1064,48,5,43,1064,41,0.854167,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
13,1,0,4,4,imp2_renamed,1064,48,5,43,1064,41,0.854167,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
14,1,0,5,5,melana_renamed,1064,49,6,43,1064,42,0.857143,0.039474,0.960526,25.333333,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
15,1,0,6,6,mrp3_renamed,1064,47,4,43,1064,41,0.872340,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
16,1,0,7,7,muc16ats_renamed,1064,48,5,43,1064,41,0.854167,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"
17,1,0,8,8,muc16tss_renamed,1064,50,6,44,1064,41,0.820000,0.038534,0.961466,25.951220,"{""AAAAAAAAA"": 41, ""AAAAACAAA"": 1}"

In [19]:
df9[(df2 != df9).any(axis=1)]

,component_id,frame_id,protein_index,protein_key,protein_name,total_nodes_associated,total_nodes_original,pep_orig_nodes,mhc_orig_nodes,frame_nodes_instances,frame_nodes_unique,node_coverage,duplication_ratio,duplication_rate,avg_multiplicity,unique_nodes_per_chain
0,0,0,0,0,bst2_renamed,1078,49,7,42,1078,41,0.836735,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
1,0,0,1,1,dse_renamed,1078,48,6,42,1078,41,0.854167,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
2,0,0,2,2,erbb2_renamed,1078,49,6,43,1078,41,0.836735,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
3,0,0,3,3,imp1_renamed,1078,48,5,43,1078,41,0.854167,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
4,0,0,4,4,imp2_renamed,1078,48,5,43,1078,41,0.854167,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
5,0,0,5,5,melana_renamed,1078,49,6,43,1078,42,0.857143,0.038961,0.961039,25.666667,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
6,0,0,6,6,mrp3_renamed,1078,47,4,43,1078,41,0.872340,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
7,0,0,7,7,muc16ats_renamed,1078,48,5,43,1078,41,0.854167,0.038033,0.961967,26.292683,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
8,0,0,8,8,muc16tss_renamed,1078,50,6,44,1078,42,0.840000,0.038961,0.961039,25.666667,"{""AAAAAAAAA"": 41, ""AAAAAAAAC"": 1, ""AAAAACAAA"":..."
9,1,0,0,0,bst2_renamed,1066,49,7,42,1066,41,0.836735,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
10,1,0,1,1,dse_renamed,1066,48,6,42,1066,41,0.854167,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
11,1,0,2,2,erbb2_renamed,1066,49,6,43,1066,41,0.836735,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
12,1,0,3,3,imp1_renamed,1066,48,5,43,1066,41,0.854167,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
13,1,0,4,4,imp2_renamed,1066,48,5,43,1066,41,0.854167,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
14,1,0,5,5,melana_renamed,1066,49,6,43,1066,42,0.857143,0.039400,0.960600,25.380952,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
15,1,0,6,6,mrp3_renamed,1066,47,4,43,1066,41,0.872340,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
16,1,0,7,7,muc16ats_renamed,1066,48,5,43,1066,41,0.854167,0.038462,0.961538,26.000000,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."
17,1,0,8,8,muc16tss_renamed,1066,50,6,44,1066,42,0.840000,0.039400,0.960600,25.380952,"{""AAAAAAAAA"": 41, ""AAAAACAAC"": 1, ""AAAAACAAA"":..."

In [5]:
crossreact = pd.read_csv("/mntSDB/carlos.simoes/GithubProjects/MHCXGraph/crossreact_analysis/crossreact_tcrs_v4.csv")

In [ ]:
crossreact.columns

,TCR_ID,TRA,TRB,peptide,MHCseq,MHCseq_ref,allele,allele_blast,mismatches,Score,...,TRA_ref,TRB_ref,TCR_pair_id,MHC_allele_id,MHC_allele_id_interface,peptide_id,pMHC_id,pep_crossreact,mhc_crossreact,pmhc_crossreact
0,PDB4ms8,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,SPAEAGFFL,MGPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRY...,GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYE...,NaN,H-2Ld,"F9Y,V13T,P16R,I24T,N31D,A50V,K132R",3,...,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,0,0,0,3,3,True,False,True
1,PDB3tjh,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,SPLDSLWWI,MGPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRY...,GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYE...,NaN,H-2Ld,"F9Y,V13T,P16R,I24T,N31D,A50V,I67V,W98R,K132R",3,...,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,0,5,1,11,11,True,False,True
2,PDB4mxq,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,SPAPRPLDL,MGPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRY...,GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYE...,NaN,H-2Ld,"F9Y,V13T,P16R,I24T,N31D,A50V,K132R",3,...,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,0,0,0,18,19,True,False,True
3,PDB3tfk,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,QLSDVPMDL,MGPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRY...,GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYE...,NaN,H-2Ld,"F9Y,V13T,P16R,I24T,N31D,A50V,I67V,W98R,K132R",3,...,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,0,5,1,89,99,True,False,True
4,PDB4n0c,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,MPAGRPWDL,MGPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRY...,GPHSMRYYETATSRRGLGEPRYTSVGYVDDKEFVRFDSDAENPRYE...,NaN,H-2Ld,"F9Y,V13T,P16R,I24T,N31D,A50V,K132R",3,...,AQSVTQPDARVTVSEGASLQLRCKYSYSATPYLFWYVQYPRQGLQM...,EAAVTQSPRNKVTVTGGNVTLSCRQTNSHNYMYWYRQDTGHGLRLI...,0,0,0,57,61,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,PDB7dzm,DAKTTQPPSMDCAEGRAANLPCNHSTISGNEYVYWYRQIHSQGPQY...,AGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELLI...,TPQDLNTML,GGSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRE...,GGSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRE...,NaN,B*81:02,A1G,3,...,DAKTTQPPSMDCAEGRAANLPCNHSTISGNEYVYWYRQIHSQGPQY...,AGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELLI...,34,25,24,74,81,False,True,False
111,PDB7dzn,DAKTTQPPSMDCAEGRAANLPCNHSTISGNEYVYWYRQIHSQGPQY...,DAGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELL...,TPQDLNTML,MGGSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPR...,GGSHSMRYFYTSVSRPGRGEPRFISVGYVDDTQFVRFDSDAASPRE...,NaN,B*42:30,A2G,3,...,DAKTTQPPSMDCAEGRAANLPCNHSTISGNEYVYWYRQIHSQGPQY...,AGVIQSPRHEVTEMGQEVTLRCKPISGHNSLFWYRQTMMRGLELLI...,34,27,25,74,88,False,True,False
112,PDB8eo8,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,AVVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLM...,LPFDKATIM,GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTE...,MRVTAPRTVLLLLWGAVALTETWAGSHSMRYFYTAMSRPGRGEPRF...,B*35:01:01:01,NaN,NaN,3,...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,VVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLMA...,35,13,9,87,97,True,False,False
113,PDB8enh,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,AVVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLM...,LPFEKSTIM,GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTE...,MRVTAPRTVLLLLWGAVALTETWAGSHSMRYFYTAMSRPGRGEPRF...,B*35:01:01:01,NaN,NaN,3,...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,VVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLMA...,35,13,9,67,74,True,False,False
114,PDB8en8,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,VVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLMA...,LPFDKSTIM,GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTE...,MRVTAPRTVLLLLWGAVALTETWAGSHSMRYFYTAMSRPGRGEPRF...,B*35:01:01:01,NaN,NaN,3,...,GENVEQHPSTLSVQEGDSAVIKCTYSDSASNYFPWYKQELGKRPQL...,VVSQHPSRVICKSGTSVKIECRSLDFQATTMFWYRQFPKQSLMLMA...,35,13,9,80,89,True,False,False

In [76]:
crossreact["PDB_ID"]

0      4MS8
1      3TJH
2      4MXQ
3      3TFK
4      4N0C
       ...
110    7DZM
111    7DZN
112    8EO8
113    8ENH
114    8EN8
Name: PDB_ID, Length: 115, dtype: str

In [31]:
crossreact["peptide_id"].max(), crossreact["TCR_pair_id"].max(),

(np.int64(90), np.int64(35))

In [32]:
for i in range(0, 91):
    p = crossreact[crossreact["peptide_id"] == i][["TCR_pair_id", "MHC_allele_id", "peptide_id"]]
    if not p.empty:
        print("---")
        print(p)
print("---")

---
   TCR_pair_id  MHC_allele_id  peptide_id
5            0              0           0
---
   TCR_pair_id  MHC_allele_id  peptide_id
9            1              1           1
---
    TCR_pair_id  MHC_allele_id  peptide_id
10            2              1           2
---
   TCR_pair_id  MHC_allele_id  peptide_id
0            0              0           3
---
    TCR_pair_id  MHC_allele_id  peptide_id
14            3              2           4
18            4              2           4
47           11              2           4
66           17              2           4
95           28              2           4
---
    TCR_pair_id  MHC_allele_id  peptide_id
21            5              2           5
---
    TCR_pair_id  MHC_allele_id  peptide_id
30            6              2           6
---
    TCR_pair_id  MHC_allele_id  peptide_id
32            7              2           7
---
    TCR_pair_id  MHC_allele_id  peptide_id
34            8              3           8
35            8              6           8
---
    TCR_pair_id  MHC_allele_id  peptide_id
24            5              2           9
---
    TCR_pair_id  MHC_allele_id  peptide_id
40            9              4          10
---
   TCR_pair_id  MHC_allele_id  peptide_id
1            0              5          11
---
    TCR_pair_id  MHC_allele_id  peptide_id
19            4              2          12
---
    TCR_pair_id  MHC_allele_id  peptide_id
42           10              2          13
---
    TCR_pair_id  MHC_allele_id  peptide_id
46           11              2          14
---
    TCR_pair_id  MHC_allele_id  peptide_id
48           12              4          15
---
    TCR_pair_id  MHC_allele_id  peptide_id
49           12              4          16
---
    TCR_pair_id  MHC_allele_id  peptide_id
50           13              2          17
---
   TCR_pair_id  MHC_allele_id  peptide_id
2            0              0          18
---
    TCR_pair_id  MHC_allele_id  peptide_id
53           14              7          19
---
   TCR_pair_id  MHC_allele_id  peptide_id
6            0              0          20
---
    TCR_pair_id  MHC_allele_id  peptide_id
56           15              2          21
---
    TCR_pair_id  MHC_allele_id  peptide_id
15            3              2          22
17            4              2          22
---
    TCR_pair_id  MHC_allele_id  peptide_id
31            7              2          23
33            7              9          23
---
    TCR_pair_id  MHC_allele_id  peptide_id
55           15              2          24
---
    TCR_pair_id  MHC_allele_id  peptide_id
58           15              2          25
---
    TCR_pair_id  MHC_allele_id  peptide_id
64           16              3          26
---
    TCR_pair_id  MHC_allele_id  peptide_id
27            5              2          27
---
    TCR_pair_id  MHC_allele_id  peptide_id
44           11              2          28
---
    TCR_pair_id  MHC_allele_id  peptide_id
60           15              2          29
---
    TCR_pair_id  MHC_allele_id  peptide_id
69           18              8          30
---
    TCR_pair_id  MHC_allele_id  peptide_id
26            5              2          31
---
    TCR_pair_id  MHC_allele_id  peptide_id
16            3              2          32
45           11              2          32
51           13              2          32
65           17              2          32
94           28              2          32
---
    TCR_pair_id  MHC_allele_id  peptide_id
71           19              7          33
72           19             10          33
---
   TCR_pair_id  MHC_allele_id  peptide_id
7            0              5          34
---
    TCR_pair_id  MHC_allele_id  peptide_id
73           20             11          35
---
   TCR_pair_id  MHC_allele_id  peptide_id
8            1              1          36
---
    TCR_pair_id  MHC_allele_id  peptide_id
59           15              2          37
---
    TCR_pair_id  MHC_allele_id  peptide_id
36            9              4          38
---
    TCR_pair_id  MHC_allele_id  peptide_id
77           21             12          39
---
    TCR_pair_id  MHC_allele_id  peptide_id
67           18             13          40
68           18             21          40
---
    TCR_pair_id  MHC_allele_id  peptide_id
63           16              3          41
---
    TCR_pair_id  MHC_allele_id  peptide_id
28            6              2          42
---
    TCR_pair_id  MHC_allele_id  peptide_id
80           22              1          43
---
    TCR_pair_id  MHC_allele_id  peptide_id
83           23             14          44
---
    TCR_pair_id  MHC_allele_id  peptide_id
82           23             15          45
---
    TCR_pair_id  MHC_allele_id  peptide_id
84           24              2          46
91           27              2          46
---
    TCR_pair_id  MHC_allele_id  peptide_id
37            9              4          47
---
    TCR_pair_id  MHC_allele_id  peptide_id
87           25             16          48
---
    TCR_pair_id  MHC_allele_id  peptide_id
88           26             18          49
90           26             17          49
---
    TCR_pair_id  MHC_allele_id  peptide_id
52           14              7          50
---
    TCR_pair_id  MHC_allele_id  peptide_id
89           26             17          51
---
    TCR_pair_id  MHC_allele_id  peptide_id
11            2              1          52
---
    TCR_pair_id  MHC_allele_id  peptide_id
54           14              7          53
---
    TCR_pair_id  MHC_allele_id  peptide_id
20            5              2          54
---
    TCR_pair_id  MHC_allele_id  peptide_id
96           29              2          55
97           29             19          55
98           29             28          55
99           29             24          55
---
     TCR_pair_id  MHC_allele_id  peptide_id
102           30             20          56
108           33             20          56
---
   TCR_pair_id  MHC_allele_id  peptide_id
4            0              0          57
---
    TCR_pair_id  MHC_allele_id  peptide_id
23            5              2          58
---
    TCR_pair_id  MHC_allele_id  peptide_id
79           21             22          59
---
     TCR_pair_id  MHC_allele_id  peptide_id
100           30             20          60
109           33             20          60
---
     TCR_pair_id  MHC_allele_id  peptide_id
103           31             23          61
---
    TCR_pair_id  MHC_allele_id  peptide_id
74           20              7          62
75           20             10          62
---
    TCR_pair_id  MHC_allele_id  peptide_id
13            3              2          63
---
    TCR_pair_id  MHC_allele_id  peptide_id
12            3              2          64
---
    TCR_pair_id  MHC_allele_id  peptide_id
38            9              4          65
---
    TCR_pair_id  MHC_allele_id  peptide_id
43           10              2          66
---
     TCR_pair_id  MHC_allele_id  peptide_id
106           32             13          67
113           35             13          67
---
    TCR_pair_id  MHC_allele_id  peptide_id
57           15              2          68
---
     TCR_pair_id  MHC_allele_id  peptide_id
105           32             13          69
---
     TCR_pair_id  MHC_allele_id  peptide_id
101           30             20          70
---
     TCR_pair_id  MHC_allele_id  peptide_id
104           31             23          71
---
    TCR_pair_id  MHC_allele_id  peptide_id
92           27              2          72
---
    TCR_pair_id  MHC_allele_id  peptide_id
29            6              2          73
---
     TCR_pair_id  MHC_allele_id  peptide_id
110           34             25          74
111           34             27          74
---
    TCR_pair_id  MHC_allele_id  peptide_id
61           15              2          75
---
    TCR_pair_id  MHC_allele_id  peptide_id
41            9              4          76
---
     TCR_pair_id  MHC_allele_id  peptide_id
107           32             13          77
---
    TCR_pair_id  MHC_allele_id  peptide_id
76           20             26          78
---
    TCR_pair_id  MHC_allele_id  peptide_id
25            5              2          79
---
     TCR_pair_id  MHC_allele_id  peptide_id
114           35             13          80
---
    TCR_pair_id  MHC_allele_id  peptide_id
78           21             22          81
---
    TCR_pair_id  MHC_allele_id  peptide_id
62           15             29          82
---
    TCR_pair_id  MHC_allele_id  peptide_id
86           25             16          83
---
    TCR_pair_id  MHC_allele_id  peptide_id
85           24              2          84
93           27              2          84
---
    TCR_pair_id  MHC_allele_id  peptide_id
70           18             13          85
---
    TCR_pair_id  MHC_allele_id  peptide_id
22            5              2          86
---
     TCR_pair_id  MHC_allele_id  peptide_id
112           35             13          87
---
    TCR_pair_id  MHC_allele_id  peptide_id
39            9              4          88
---
   TCR_pair_id  MHC_allele_id  peptide_id
3            0              5          89
---
    TCR_pair_id  MHC_allele_id  peptide_id
81           22              1          90
---

In [33]:
for i in range(0, 36):
    p = crossreact[crossreact["TCR_pair_id"] == i][["TCR_pair_id", "MHC_allele_id", "peptide_id"]]
    if not p.empty:
        print("---")
        print(p)
print("---")

---
   TCR_pair_id  MHC_allele_id  peptide_id
0            0              0           3
1            0              5          11
2            0              0          18
3            0              5          89
4            0              0          57
5            0              0           0
6            0              0          20
7            0              5          34
---
   TCR_pair_id  MHC_allele_id  peptide_id
8            1              1          36
9            1              1           1
---
    TCR_pair_id  MHC_allele_id  peptide_id
10            2              1           2
11            2              1          52
---
    TCR_pair_id  MHC_allele_id  peptide_id
12            3              2          64
13            3              2          63
14            3              2           4
15            3              2          22
16            3              2          32
---
    TCR_pair_id  MHC_allele_id  peptide_id
17            4              2          22
18            4              2           4
19            4              2          12
---
    TCR_pair_id  MHC_allele_id  peptide_id
20            5              2          54
21            5              2           5
22            5              2          86
23            5              2          58
24            5              2           9
25            5              2          79
26            5              2          31
27            5              2          27
---
    TCR_pair_id  MHC_allele_id  peptide_id
28            6              2          42
29            6              2          73
30            6              2           6
---
    TCR_pair_id  MHC_allele_id  peptide_id
31            7              2          23
32            7              2           7
33            7              9          23
---
    TCR_pair_id  MHC_allele_id  peptide_id
34            8              3           8
35            8              6           8
---
    TCR_pair_id  MHC_allele_id  peptide_id
36            9              4          38
37            9              4          47
38            9              4          65
39            9              4          88
40            9              4          10
41            9              4          76
---
    TCR_pair_id  MHC_allele_id  peptide_id
42           10              2          13
43           10              2          66
---
    TCR_pair_id  MHC_allele_id  peptide_id
44           11              2          28
45           11              2          32
46           11              2          14
47           11              2           4
---
    TCR_pair_id  MHC_allele_id  peptide_id
48           12              4          15
49           12              4          16
---
    TCR_pair_id  MHC_allele_id  peptide_id
50           13              2          17
51           13              2          32
---
    TCR_pair_id  MHC_allele_id  peptide_id
52           14              7          50
53           14              7          19
54           14              7          53
---
    TCR_pair_id  MHC_allele_id  peptide_id
55           15              2          24
56           15              2          21
57           15              2          68
58           15              2          25
59           15              2          37
60           15              2          29
61           15              2          75
62           15             29          82
---
    TCR_pair_id  MHC_allele_id  peptide_id
63           16              3          41
64           16              3          26
---
    TCR_pair_id  MHC_allele_id  peptide_id
65           17              2          32
66           17              2           4
---
    TCR_pair_id  MHC_allele_id  peptide_id
67           18             13          40
68           18             21          40
69           18              8          30
70           18             13          85
---
    TCR_pair_id  MHC_allele_id  peptide_id
71           19              7          33
72           19             10          33
---
    TCR_pair_id  MHC_allele_id  peptide_id
73           20             11          35
74           20              7          62
75           20             10          62
76           20             26          78
---
    TCR_pair_id  MHC_allele_id  peptide_id
77           21             12          39
78           21             22          81
79           21             22          59
---
    TCR_pair_id  MHC_allele_id  peptide_id
80           22              1          43
81           22              1          90
---
    TCR_pair_id  MHC_allele_id  peptide_id
82           23             15          45
83           23             14          44
---
    TCR_pair_id  MHC_allele_id  peptide_id
84           24              2          46
85           24              2          84
---
    TCR_pair_id  MHC_allele_id  peptide_id
86           25             16          83
87           25             16          48
---
    TCR_pair_id  MHC_allele_id  peptide_id
88           26             18          49
89           26             17          51
90           26             17          49
---
    TCR_pair_id  MHC_allele_id  peptide_id
91           27              2          46
92           27              2          72
93           27              2          84
---
    TCR_pair_id  MHC_allele_id  peptide_id
94           28              2          32
95           28              2           4
---
    TCR_pair_id  MHC_allele_id  peptide_id
96           29              2          55
97           29             19          55
98           29             28          55
99           29             24          55
---
     TCR_pair_id  MHC_allele_id  peptide_id
100           30             20          60
101           30             20          70
102           30             20          56
---
     TCR_pair_id  MHC_allele_id  peptide_id
103           31             23          61
104           31             23          71
---
     TCR_pair_id  MHC_allele_id  peptide_id
105           32             13          69
106           32             13          67
107           32             13          77
---
     TCR_pair_id  MHC_allele_id  peptide_id
108           33             20          56
109           33             20          60
---
     TCR_pair_id  MHC_allele_id  peptide_id
110           34             25          74
111           34             27          74
---
     TCR_pair_id  MHC_allele_id  peptide_id
112           35             13          87
113           35             13          67
114           35             13          80
---

In [64]:
crossDict = {}

for i in range(37):
    crossDict[i] = {"sim": set(), "não": set()}

for i in range(37):
    TCR_1 = set(crossreact[crossreact["peptide_id"] == i]["TCR_pair_id"].tolist())

    for j in range(i + 1, 37):
        TCR_2 = set(crossreact[crossreact["peptide_id"] == j]["TCR_pair_id"].tolist())

        cross = TCR_1.intersection(TCR_2)

        if len(cross) == 0:
            crossDict[i]["não"].add(j)
            crossDict[j]["não"].add(i)
        else:
            crossDict[i]["sim"].add(j)
            crossDict[j]["sim"].add(i)

In [65]:
groups = {}

for i in crossDict.keys():
    peps = crossDict[i]["não"]

    if not peps:
        groups[i] = set()
        continue

    intersection = set.intersection(*(crossDict[pep]["não"] for pep in peps))

    # remove o próprio peptide se aparecer
    intersection.discard(i)

    groups[i] = intersection

In [73]:
groupsUnique = []
for i in groups.keys():
    groups[i].add(i)
    if tuple(groups[i]) not in groupsUnique:
        if len(groups[i]) > 1:
            groupsUnique.append(tuple(groups[i]))

In [74]:
groupsUnique

[(0, 34, 3, 11, 18, 20),
 (1, 36),
 (4, 12, 14, 22, 28),
 (9, 27, 5, 31),
 (23, 7),
 (28, 14),
 (16, 15),
 (24, 25, 21, 29),
 (12, 22),
 (32, 17, 28, 14)]